server:
  port: 8888          # Config Server port

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ManikyaAnilkumar/config-repo
          clone-on-start: true
          default-label: main
